### ISSUE TITLE
Can this list be updated as apps are updated to support WebID-OIDC?

### ISSUE THREAD

**Issue by reinvented** [solid/solid-apps#10]
It would be nice to have this list updated as apps are updated to support WebID-OIDC.

I've had some success, using the [dz_oidc branch of solid-server](https://github.com/solid/node-solid-server/tree/dz_oidc) with getting the following to work:

* https://github.com/linkeddata/profile-editor
* https://github.com/linkeddata/warp

**Comment by Mitzi-Laszlo** [comment]
Hi @reinvented, 

Thank you for your input, let me know if there are any concrete actions you suggest to take and how to go about it.

Mitzi

**Comment by TallTed** [comment]
Switching from streaming-text bullet items to a grid/table of information about each app would help in tracking and viewing details like this, though editing tables in markdown can be an exercise in frustration.

Building such tables in HTML (rather than markdown) can make editing and viewing the raw data easier, *if* treated as HTML-within-`.md` instead of `.html` code within github.

Switching to RDF (probably serialized in Turtle) would be more "dog-food" style, but would introduce a fair bit of extra complexity to the editing and presentation process.

**Comment by jeff-zucker** [comment]
+1 to listing apps in Turtle!
```Turtle
<https://git-hub.com/jeff-zucker/solid-rest>
    a x:App;
    x:creator [x:name "Jeff Zucker", x:homepage <...>];
    x:description "A client-side API which supports any backend for Solid requests"
    x:copyright "MIT, 2019"
.
```

**Comment by TallTed** [comment]
Downside of switching to RDF/Turtle: complex objects (like values of `x:description` are likely to be) often want embedded/inline markup -- which is non-trivial to handle properly.

Simple string-literals are well-and-truly plain-text, and authors must revert to old Usenet-style human-parsed markup (`_emphasis_ by *wrappers*` vs markdown-processed _emphasis_ by **wrappers**, and no live-links) -- unless an extra processor is handling things.

Staying with markdown (or HTML-within-markdown) on github means that the pages get rendered to a user-friendly, easily read form.

As usual, there are tradeoffs to be considered everywhere...
