### ISSUE TITLE
Interoperability

### ISSUE THREAD

**Issue by Mitzi-Laszlo** [solid/solid-apps#57]
Based on the [scope of the Solid specification](https://github.com/solid/specification/issues/29) it should be possible for a user to use one app, leave it, bring the data, and reuse it in another app. 

Of the [listed Solid apps](https://github.com/solid/solid-apps) in which is it possible for the user to use one app, decide to leave it, and bring the data along to another app? 

In the apps where it is not possible, why is this not possible? 

Similarly, there are two [Pods listed](https://github.com/solid/pods). How can users switch between the two and bring their data along? 

If this is not possible, why not?

**Comment by Vinnl** [comment]
> Of the listed Solid apps in which is it possible for the user to use one app, decide to leave it, and bring the data along to another app?

I know Poddit and Markbook are interoperable, because I made Poddit to be so :)

> In the apps where it is not possible, why is this not possible?

Either because they just do different things, or the authors did not make sure they were using the same data model (e.g. where one refers to "name" and the other to "first name").

> Similarly, there are two Pods listed. How can users switch between the two and bring their data along?

I think "Pod" should be "Pod provider"? Pod servers could provide the option to export and import the data, but I don't think any of the existing ones do so yet.

**Comment by Mitzi-Laszlo** [comment]
Ok - in that case, I've started making a [list about personal data describing a single person](https://github.com/solid/data-interoperability-panel/pull/7) so we know the parameters of what data needs to interoperate around an individual.
